services:
  metabase:
    image: metabase/metabase:v0.48.1
    restart: always
    container_name: metabase
    ports:
      - "3000:3000"
    volumes:
      - /data/metabase-data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
